version: '2'
services:
  driverapp-app:
    image: driverapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://driverapp-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=driverApp
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://driverapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://driverapp-elasticsearch:9200
  driverapp-mongodb:
    extends:
      file: mongodb.yml
      service: driverapp-mongodb
  driverapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: driverapp-elasticsearch
